## 作業
# 輸入一串數字5,6,7
# 幫我存到檔案mydata.txt
# 讀取mydata.txt 並加總數字

In [1]:
import os
print(os.getcwd())

C:\Users\xvpow\ai_20251229\ch14


In [2]:
txt = input("請輸入一串數字用逗號隔開")
with open("mydata.txt","w",encoding="utf-8") as f:
    f.write(txt)
print("寫出成功")    

請輸入一串數字用逗號隔開 5,6,7


寫出成功


In [7]:
mySum = 0
with open("mydata.txt","r",encoding="utf-8") as f:
    content = f.read()
    print(content)
    strList = content.split(",")
    print(strList)
    for v in strList:
        mySum += int(v)
print("sum:",mySum)        

5,6,7
['5', '6', '7']
sum: 18


In [10]:
mySum = 0
with open("mydata.txt","r",encoding="utf-8") as f:
    content = f.read()
    print(content)
    strList = content.split(",")
    intList = list(map(int,strList))
    for v in intList:
        mySum += v
print("sum:",mySum)  

5,6,7
sum: 18


## 電影排行榜

In [42]:
import requests
from bs4 import BeautifulSoup
url = "https://zh.wikipedia.org/zh-tw/2025年电影"
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                  "AppleWebKit/537.36 (KHTML, like Gecko) "
                  "Chrome/120.0.0.0 Safari/537.36"
}
resp = requests.get(url,headers = headers)
resp.encoding="utf-8"
#print(resp.text)
soup = BeautifulSoup(resp.text,"html5lib")
movieTable = soup.find("table",class_="wikitable sortable")
tbody = movieTable.find("tbody")
trList = tbody.find_all("tr")
for i in range(1,len(trList)):
    print("排名:",trList[i].find("th").getText(),end="")
    print("片名:",trList[i].select_one("a").text)
    print("全球票房:",trList[i].find_all("td")[-1].text)


排名: 1
片名: 哪吒之魔童鬧海
全球票房: $2,178,381,023

排名: 2
片名: 動物方城市2
全球票房: $1,803,494,832

排名: 3
片名: 阿凡達：火與燼
全球票房: $1,439,895,218

排名: 4
片名: 星際寶貝：史迪奇
全球票房: $1,038,027,526

排名: 5
片名: MINECRAFT麥塊電影
全球票房: $961,187,780

排名: 6
片名: 侏羅紀世界：重生
全球票房: $869,146,189

排名: 7
片名: 「鬼滅之刃」無限城篇
全球票房: $778,939,527

排名: 8
片名: 馴龍高手
全球票房: $636,351,148

排名: 9
片名: F1電影
全球票房: $633,142,436

排名: 10
片名: 超人
全球票房: $618,723,803



## Numpy
+ 可做到的功能
  + 快速的多維陣列操作。
  + 可靠的科學功能函數庫。
  + 可協助繪圖工具進行繪圖。
+ NumPy 是幾乎每個科學 Python 應用程序或模組的核心，它提供了以向量化形式的快速 N-d 陣列類型可供操作。

In [39]:
import numpy as np
a = [1,2,3,5,7,9]
b = [3,5,3,6,7,9]
print(type(a))
np1 = np.array(a)
np2 = np.array(b)
print(a,b)
print(np1,np2)
print(a+b)
print(np1+np2)

<class 'list'>
[1, 2, 3, 5, 7, 9] [3, 5, 3, 6, 7, 9]
[1 2 3 5 7 9] [3 5 3 6 7 9]
[1, 2, 3, 5, 7, 9, 3, 5, 3, 6, 7, 9]
[ 4  7  6 11 14 18]


+ ndarray.ndim
   + 維度的數量。
+ ndarray.shape
   + 顯示出陣列在每個維度上的整數值。
+ ndarray.size
   + 陣列內元素的總數。
+ ndarray.dtype
   + 用來描述陣列中元素類型的對象。

In [50]:
import numpy as np
i = [[1,2,3],
     [ 4,5,6 ]]#2x3 矩陣
a = np.array(i)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

2
(2, 3)
6
int32


In [53]:
import numpy as np
a = np.array([6,7,8,9])
b = np.arange(4)
print(a)
print(b)
c = a - b
print(c)
e = b ** 2
print(e)

[6 7 8 9]
[0 1 2 3]
[6 6 6 6]
[0 1 4 9]


In [57]:
import numpy as np
f = np.array([5,-1,3,9,0])
boolArr = f <= 3
print(boolArr)
print(f[boolArr])
print(f[f <= 3])

[False  True  True False  True]
[-1  3  0]
[-1  3  0]


In [1]:
import numpy as np
x = np.empty((2,4))
print(x)
x = np.zeros((2,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
import numpy as np
x = np.ones((2,4))
print(x)
x = np.full((2,4),6)
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[6 6 6 6]
 [6 6 6 6]]


In [17]:
import numpy as np
x = np.eye(3)
print(x)#I 單位矩陣 數學定義上矩陣的1
x = np.diag([1,2,3,4])
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


### linspace arange

+ linspace(a,b,c,)
   + 包含 b 由 a 開始 切割成 c 個資料
+ linspace(a,b,c,endpoint=False)
   + 不包含 b 由 a 開始 切割成 c 個資料

In [31]:
import numpy as np
x = np.linspace(1,10,6)# (10-1)/(6-1)
print(x)
x = np.linspace(1,10,6,endpoint=False)# (10-1)/(6) 
print(x)

[ 1.   2.8  4.6  6.4  8.2 10. ]
[1.  2.5 4.  5.5 7.  8.5]


In [33]:
x = np.linspace(1,10,6).reshape((2,3))
print(x)

[[ 1.   2.8  4.6]
 [ 6.4  8.2 10. ]]


In [38]:
x = np.arange(8).reshape((2,4))
print(x)

[[0 1 2 3]
 [4 5 6 7]]


In [39]:
#3~5 包含5 取9各3~5內的插值
lin = np.linspace(3,5,9)
print(lin)

[3.   3.25 3.5  3.75 4.   4.25 4.5  4.75 5.  ]
